spring:
  data:
    mongodb:
      uri: mongodb+srv://lakshitlohar02:18ll_2002@cluster0.dhec31z.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database : journaldb
      auto-index-creation : true
  mail:
    host: smtp.gmail.com
    port: 587
    username: randomaadmi@gmail.com
    password: xxxx xxxx xxxx xxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
  servlet:
    context-path: /journal

weather:
  api:
    key: 58edbd770fb8cf486a399bf5d0831c04